apiVersion: apps/v1
kind: Deployment
metadata:
  name: userregistry-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userregistry-api
  template:
    metadata:
      labels:
        app: userregistry-api
    spec:
      containers:
      - name: userregistry-api
        image: sandycis476/register:latest
        ports:
        - containerPort: 8084
--- 
apiVersion: v1
kind: Service
metadata:
  name: userregistry-api
spec:
  selector:
    app: userregistry-api
  ports:
  - protocol: TCP
    port: 8084         # Port exposed to the Ingress
    targetPort: 8084 # Port in the application pod
  type: ClusterIP


