package com.dataquadinc.model;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDate;
import java.time.LocalDateTime;
import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
@Table(
        name = "Employee_attendance_IN",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_employee_attendance",
                        columnNames = {
                                "employee_id",
                                "attendance_date"
                        }
                )
        }
)
@Data
public class EmployeeAttendance {

    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "month_config_id")
    private AttendanceMonthConfig monthConfig;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    private String employeeId;

    private String employeeName;

    private LocalDate attendanceDate;

    private Integer attendanceMonth;

    private Integer attendanceYear;

    /*
    P  = Present
    L  = Leave
    WH = Work From Home
    HD = Half Day
    LL = Late Login
    WO = Weekend
    SP  = Special Leave
    LOP = Loss Of Pay
    PH = Public Holiday
     */
    private String attendanceStatus;

    /*
     For HD:
     1.0 = Full day
     0.5 = Half day
     */
    private Double attendanceValue = 1.0;

    private String reportingManager;

    /*
     Week blocks:
     1 = 26–1
     2 = 2–8
     3 = 9–15
     4 = 16–22
     5 = 23–25
     */
    private Integer weekNumber;

    /*
    DRAFT
    SUBMITTED
    APPROVED
     */
    private String approvalStatus = "DRAFT";

    private Boolean isLocked = false;

    /*
    month cycle dates

    Example:
    month=6 year=2026

    fromDate = 2026-05-26
    toDate   = 2026-06-25
     */
    private LocalDate fromDate;

    private LocalDate toDate;

    /*
    Auto generated by HR month setup
     */
    private Boolean isPublicHoliday = false;

    private Boolean isWeekend = false;

    @Column(length = 500)
    private String remarks;

    @Column(nullable = false)
    private Boolean isSandwichDeduction = false;

    @Column(nullable = false)
    private Boolean isPaid = true;

    @Column(nullable = false)
    private Boolean isProbationEmployee = false;

    @Column(nullable = false)
    private Boolean casualLeaveApplied = false;

    @Column(nullable = false)
    private Boolean salaryDeduction = false;

    private String createdBy;

    private String updatedBy;

    private LocalDateTime submittedAt;

    private LocalDateTime approvedAt;

    @Column(updatable = false)
    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    @PrePersist
    public void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    public void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
